services:
  - name: server
    plan: free
    type: web
    env: node
    repo: https://github.com/tati-guzman/click-and-treat.git
    buildCommand: cd client && npm install && npm run build && cd ../server && npm install
    startCommand: cd server && node server.js && cd .. && cd client && npm run dev
    envVars:
      - key: DB_URI
        fromDatabase:
          name: db
          property: connectionString

databases:
  - name: clickandtreat
    plan: free
    ipAllowList: []